---
- name: Add user to group, install Docker, Buildkite agent, and fonts
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - docker
    - buildkite
    - fonts

  tasks:
    - name: ping nodes
      ping:
      register: ping_result

    - debug:
        var: ping_result


    - name: Add user to sudo group
      user:
        name: "{{ user_name }}"
        groups: "{{ sudo_group_name }}"
        append: yes
