---
- name: Install prerequisites
  apt:
    name: "{{ prerequisite_packages }}"
    state: present

- name: Add Docker's GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch={{ dpkg_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Add user to docker group
  user:
    name: "{{ user_name }}"
    groups: "{{ docker_group_name }}"
    append: yes
