# User and group names
user_name: "rsherman"
sudo_group_name: "sudo"
docker_group_name: "docker"

# Prerequisite packages
prerequisite_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common

# Docker packages
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin