---
- name: Download font files
  get_url:
    url: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
  loop:
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"

- name: Install fonts
  shell: |
    cp /tmp/*.ttf /usr/share/fonts/
    fc-cache -f -v
