---
- name: Download font files
  get_url:
    url: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
  loop: "{{ font_urls }}"

- name: Install fonts
  shell: |
    cp /tmp/*.ttf /usr/share/fonts/
    fc-cache -f -v
